name: "Code Generation Pipeline"
description: "A sequential workflow for generating, reviewing, and refactoring code"
version: "1.0.0"

api_config:
  provider: "gemini"
  model: "gemini-1.5-flash"
  temperature: 0.0
  max_tokens: 2048
  timeout: 60

steps:
  - name: "CodeWriterAgent"
    model: "gemini-1.5-flash"
    prompt_key: "code_writer"
    description: "Writes initial Python code based on a specification"
    output_key: "generated_code"
    parameters:
      temperature: 0.0
      max_tokens: 2048

  - name: "CodeReviewerAgent"
    model: "gemini-1.5-flash"
    prompt_key: "code_reviewer"
    description: "Reviews code and provides feedback"
    output_key: "review_comments"
    parameters:
      temperature: 0.0
      max_tokens: 1024

  - name: "CodeRefactorerAgent"
    model: "gemini-1.5-flash"
    prompt_key: "code_refactorer"
    description: "Refactors code based on review comments"
    output_key: "refactored_code"
    parameters:
      temperature: 0.0
      max_tokens: 2048

metadata:
  author: "Your Name"
  created_at: "2024-03-20"
  tags:
    - "code-generation"
    - "code-review"
    - "refactoring" 