# Gemini LLM Configuration
# Primary: API key configured here in YAML
# Fallback: GOOGLE_API_KEY environment variable

# Basic LLM Configuration
provider: "gemini"
model: "gemini-1.5-flash"
temperature: 0.0
max_tokens: 2048

# API Configuration
api_config:
  api_key: "AIzaSyCs7T6qdSPA3r16W_q01fCzKZvn-5DAioI"
  timeout: 60

# Backend Configuration
backend: "google"

# Step-specific Models
step_models:
  0: "gemini-1.5-flash"  # CodeWriterAgent
  1: "gemini-1.5-flash"  # CodeReviewerAgent
  2: "gemini-1.5-flash"  # CodeRefactorerAgent

# Gemini-specific Configuration (used by the provider, not LLMConfig)
generation_config:
  top_p: 0.95
  top_k: 40
  candidate_count: 1
  stop_sequences: []
  max_output_tokens: 2048
  temperature: 0.7

# Safety Settings (used by the provider, not LLMConfig)
safety_settings:
  - category: "HARM_CATEGORY_HARASSMENT"
    threshold: "BLOCK_MEDIUM_AND_ABOVE"
  - category: "HARM_CATEGORY_HATE_SPEECH"
    threshold: "BLOCK_MEDIUM_AND_ABOVE"
  - category: "HARM_CATEGORY_SEXUALLY_EXPLICIT"
    threshold: "BLOCK_MEDIUM_AND_ABOVE"
  - category: "HARM_CATEGORY_DANGEROUS_CONTENT"
    threshold: "BLOCK_MEDIUM_AND_ABOVE"

# Metadata
metadata:
  version: "1.0"
  description: "Configuration for Gemini LLM provider"
  last_updated: "2024-06-04" 