# Gemini API Configuration for Flexible Agent Workflow
# This file contains configuration for Google's Gemini API integration

# API Configuration
api_config:
  provider: "gemini"
  
  # API Key - Set your Google API key here
  # You can also set this via environment variable: GOOGLE_API_KEY
  api_key: "AIzaSyCs7T6qdSPA3r16W_q01fCzKZvn-5DAioI"
  
  # Default model to use
  default_model: "gemini-2.0-flash"
  
  # API endpoints
  base_url: "https://generativelanguage.googleapis.com"
  api_version: "v1beta"

# Model Configuration
model_config:
  # Available models with their configurations
  models:
    gemini-1.5-pro:
      max_tokens: 8192
      supports_tools: true
      supports_multimodal: true
      cost_tier: "premium"
      
    gemini-1.5-flash:
      max_tokens: 4096
      supports_tools: true
      supports_multimodal: true
      cost_tier: "standard"
      
    gemini-1.0-pro:
      max_tokens: 4096
      supports_tools: false
      supports_multimodal: false
      cost_tier: "basic"

# Performance Configuration
performance_config:
  # Request timeout in seconds
  timeout_seconds: 120
  
  # Retry configuration
  max_retries: 3
  retry_delay: 1.0
  backoff_factor: 2.0
  
  # Rate limiting
  max_requests_per_minute: 60
  max_tokens_per_minute: 32000
  
  # Connection pooling
  max_connections: 10
  keep_alive: true

# Security Configuration
security_config:
  # Validate SSL certificates
  verify_ssl: true
  
  # Content filtering
  enable_safety_settings: true
  
  # Block categories (adjust as needed)
  safety_settings:
    HARM_CATEGORY_HARASSMENT: "BLOCK_MEDIUM_AND_ABOVE"
    HARM_CATEGORY_HATE_SPEECH: "BLOCK_MEDIUM_AND_ABOVE"
    HARM_CATEGORY_SEXUALLY_EXPLICIT: "BLOCK_MEDIUM_AND_ABOVE"
    HARM_CATEGORY_DANGEROUS_CONTENT: "BLOCK_MEDIUM_AND_ABOVE"

# Generation Configuration Defaults
generation_config:
  # Default temperature for flexible agent workflows
  temperature: 0.0
  
  # Token limits
  max_output_tokens: 4096
  
  # Sampling parameters
  top_p: 0.95
  top_k: 40
  
  # Stop sequences
  stop_sequences: []
  
  # Candidate count
  candidate_count: 1

# Flexible Agent Specific Configuration
flexible_agent_config:
  # Model selection strategy for different agent types
  agent_model_mapping:
    RequirementAnalyzer: "gemini-2.0-flash"
    ArchitecturalDesigner: "gemini-2.0-flash"
    CodeGenerator: "gemini-2.0-flash"
    SecurityReviewer: "gemini-2.0-flash"
    PerformanceReviewer: "gemini-2.0-flash"
    QualityReviewer: "gemini-2.0-flash"
    CodeRefactorer: "gemini-2.0-flash"
    DocumentationGenerator: "gemini-2.0-flash"
    
  # Temperature settings for different agent types
  agent_temperature_mapping:
    RequirementAnalyzer: 0.1
    ArchitecturalDesigner: 0.0
    CodeGenerator: 0.0
    SecurityReviewer: 0.0
    PerformanceReviewer: 0.0
    QualityReviewer: 0.0
    CodeRefactorer: 0.0
    DocumentationGenerator: 0.1
    
  # Enable/disable features per agent type
  agent_features:
    parallel_processing: true
    tool_calling: true
    multimodal_input: false
    streaming_response: false

# Logging Configuration
logging_config:
  # Log level for API calls
  log_level: "INFO"
  
  # Log API requests and responses
  log_requests: true
  log_responses: false  # Set to true for debugging (may contain sensitive data)
  
  # Log file location
  log_file: "flexible_agent_api.log"
  
  # Log rotation
  max_log_size_mb: 100
  backup_count: 5

# Development Configuration
development_config:
  # Enable debug mode
  debug_mode: false
  
  # Mock API responses for testing
  mock_responses: false
  
  # Validate configurations on startup
  validate_config: true
  
  # Enable metrics collection
  enable_metrics: true

# Monitoring Configuration
monitoring_config:
  # Track API usage
  track_usage: true
  
  # Usage limits and alerts
  daily_token_limit: 1000000
  alert_threshold: 0.8  # Alert when 80% of limit is reached
  
  # Performance monitoring
  track_latency: true
  track_errors: true
  
  # Health check configuration
  health_check_interval: 300  # seconds
  health_check_timeout: 30    # seconds

metadata:
  created_at: "2024-12-20"
  version: "2.0.0"
  description: "Gemini API configuration for flexible agent workflow system"
  author: "System" 